kind: Namespace
apiVersion: v1
metadata:
  name: goshelly
  labels:
    name: goshelly

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: goshelly
provisioner: docker.io/hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: goshelly
  namespace: goshelly
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/goshelly"
  storageClassName: goshelly
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goshelly
  namespace: goshelly
spec:
  storageClassName: goshelly
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Pod
metadata:
  name: goshelly
  namespace: goshelly
spec:
  volumes:
    - name: goshelly
      persistentVolumeClaim:
        claimName: goshelly
  containers:
    - name: goshelly
      image: ubuntu:latest
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
        - mountPath: "/mnt/goshelly"
          name: goshelly
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-all
  namespace: goshelly
spec:
  podSelector:
    matchLabels:
      app: goshelly
  ingress:
    - {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goshelly
  namespace: goshelly
  labels:
    app: goshelly
spec:
  replicas: 2
  selector:
    matchLabels:
      app: goshelly
  template:
    metadata:
      labels:
        app: goshelly
    spec:
      restartPolicy: Always
      containers:
        - name: goshelly
          image: arorasoham9/goshelly-server:linux
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/mnt/goshelly"
              name: goshelly
      volumes:
        - name: goshelly
          persistentVolumeClaim:
            claimName: goshelly
---

